### ISSUE TITLE
the next button in panel without filmstrip is messed up

### ISSUE THREAD

**Issue by ghost** [hybridindie/WordPress-Nextgen-GalleryView#7]
teste in chrome 13, ie7, firefox 6.02

fix is quit easy, just add the dimensions on line 390 and 399 in .js

```
'width':'22px',
'height':'22px'
```

or add to theme style 

``` css
.galleryview img.nav-next,
.galleryview img.nav-prev {
  width:22px;
  height:22px;
}
```
